development:
  adapter: postgresql
  encoding: utf8
  database: boxylib_dev
  host: localhost

test: &test
  adapter: postgresql
  encoding: utf8
  database: boxylib_test
  host: localhost

cucumber:
  <<: *test
